import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type ComponentHeroModel = IContentItem<{
  image: Elements.AssetsElement;
  ctaLink: Elements.TextElement;
  ctaText: Elements.TextElement;
  headline: Elements.TextElement;
  subheadline: Elements.TextElement;
}>;
