import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type ComponentTextWithImageModel = IContentItem<{
  headline: Elements.TextElement;
  image: Elements.AssetsElement;
  text: Elements.RichTextElement;
}>;
